// API Configuration
const JOKE_API_URL = 'https://v2.jokeapi.dev/joke';

// DOM Elements
const categorySelect = document.getElementById('category');
const getJokeBtns = document.querySelectorAll('#getJokeBtn, #getJokeBtn2');
const jokeContainer = document.getElementById('jokeContainer');
const jokeContent = document.getElementById('jokeContent');
const loadingDiv = document.getElementById('loading');
const errorDiv = document.getElementById('error');
const errorMessage = document.getElementById('errorMessage');
const copyBtn = document.getElementById('copyBtn');
const shareTwitterBtn = document.getElementById('shareTwitterBtn');
const themeToggle = document.getElementById('themeToggle');

// Store current joke for sharing/copying
let currentJoke = '';
let currentJokeObj = null;

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    loadTheme();
    setupEventListeners();
});

// Setup Event Listeners
function setupEventListeners() {
    getJokeBtns.forEach(btn => {
        btn.addEventListener('click', fetchJoke);
    });

    copyBtn.addEventListener('click', copyJoke);
    shareTwitterBtn.addEventListener('click', shareOnTwitter);
    themeToggle.addEventListener('click', toggleTheme);
    categorySelect.addEventListener('change', fetchJoke);
}

// Fetch Joke from API
async function fetchJoke() {
    const category = categorySelect.value;
    const url = `${JOKE_API_URL}/${category}`;

    // Show loading, hide others
    showLoading();
    hideError();
    hideJoke();

    try {
        const response = await fetch(url);

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();

        if (data.error) {
            showError('No jokes found for this category');
            return;
        }

        // Store joke data
        currentJokeObj = data;
        displayJoke(data);
    } catch (error) {
        console.error('Error fetching joke:', error);
        showError('Failed to fetch joke. Please check your internet connection and try again.');
    }
}

// Display Joke
function displayJoke(jokeData) {
    hideLoading();

    let jokeHTML = '';

    if (jokeData.type === 'single') {
        // Single line joke
        currentJoke = jokeData.joke;
        jokeHTML = `<p>${escapeHtml(jokeData.joke)}</p>`;
    } else if (jokeData.type === 'twopart') {
        // Two-part joke (setup + delivery)
        currentJoke = `${jokeData.setup}\n\n${jokeData.delivery}`;
        jokeHTML = `
            <div class="joke-setup">${escapeHtml(jokeData.setup)}</div>
            <div class="joke-delivery">${escapeHtml(jokeData.delivery)}</div>
        `;
    }

    jokeContent.innerHTML = jokeHTML;
    showJoke();
}

// Show/Hide Functions
function showLoading() {
    loadingDiv.classList.remove('hidden');
}

function hideLoading() {
    loadingDiv.classList.add('hidden');
}

function showError(message) {
    errorMessage.textContent = message;
    errorDiv.classList.remove('hidden');
}

function hideError() {
    errorDiv.classList.add('hidden');
}

function showJoke() {
    jokeContainer.classList.remove('hidden');
}

function hideJoke() {
    jokeContainer.classList.add('hidden');
}

// Copy Joke to Clipboard
async function copyJoke() {
    try {
        await navigator.clipboard.writeText(currentJoke);
        showCopyFeedback();
    } catch (error) {
        console.error('Failed to copy:', error);
        alert('Failed to copy joke');
    }
}

// Show Copy Feedback
function showCopyFeedback() {
    // Create feedback element
    const feedback = document.createElement('div');
    feedback.className = 'copy-feedback';
    feedback.textContent = '✓ Copied to clipboard!';
    document.body.appendChild(feedback);

    // Remove after 2 seconds
    setTimeout(() => {
        feedback.classList.add('hidden');
        feedback.remove();
    }, 2000);
}

// Share on Twitter
function shareOnTwitter() {
    if (!currentJoke) return;

    const twitterText = encodeURIComponent(`Just laughed at this joke: "${currentJoke}" 😂\n\nGenerated by @JokeAPIdev`);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${twitterText}`;
    window.open(twitterUrl, '_blank', 'width=550,height=420');
}

// Theme Toggle
function toggleTheme() {
    const isDarkMode = document.body.classList.toggle('dark-mode');
    localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
}

// Load Saved Theme
function loadTheme() {
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'dark') {
        document.body.classList.add('dark-mode');
    }
}

// Escape HTML to prevent XSS
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

// Preload first joke on page load
window.addEventListener('load', () => {
    // Auto-fetch a joke on page load
    setTimeout(() => {
        fetchJoke();
    }, 300);
});
